class TASK
	 @@res1 = LONG_RESOURCE.new
	 @@res2 = SHORT_RESOURCE.new
	 @@res3 = LONG_RESOURCE.new
	 @@res4 = SHORT_RESOURCE.new
	 @@res5 = LONG_RESOURCE.new
	 @@res6 = SHORT_RESOURCE.new
	 @@res7 = LONG_RESOURCE.new
	 @@res8 = SHORT_RESOURCE.new
	 @@share1 = 1.0
	 def task1
		 exc(18 * @@share1)
		 GetLongResource(@@res1)
		 exc(1)
		 ReleaseLongResource(@@res1)
		 exc(8 * @@share1)
		 GetLongResource(@@res1)
		 exc(3)
		 ReleaseLongResource(@@res1)
		 exc(9 * @@share1)
		 GetShortResource(@@res4)
		 exc(3)
		 ReleaseShortResource(@@res4)
		 exc(1 * @@share1)
	 end
	 def task5
		 exc(12 * @@share1)
		 GetLongResource(@@res1)
		 exc(1)
		 ReleaseLongResource(@@res1)
		 GetLongResource(@@res1)
		 exc(1)
		 ReleaseLongResource(@@res1)
		 exc(6 * @@share1)
		 GetLongResource(@@res7)
		 exc(1)
		 ReleaseLongResource(@@res7)
		 exc(13 * @@share1)
	 end
	 def task9
		 exc(24 * @@share1)
		 GetLongResource(@@res1)
		 exc(1)
		 ReleaseLongResource(@@res1)
		 exc(2 * @@share1)
		 GetLongResource(@@res3)
		 exc(4)
		 ReleaseLongResource(@@res3)
		 exc(11 * @@share1)
		 GetShortResource(@@res4)
		 exc(3)
		 ReleaseShortResource(@@res4)
		 exc(2 * @@share1)
	 end
	 def task13
		 exc(12 * @@share1)
		 GetLongResource(@@res1)
		 exc(2)
		 ReleaseLongResource(@@res1)
		 exc(1 * @@share1)
		 GetShortResource(@@res4)
		 exc(3)
		 ReleaseShortResource(@@res4)
		 exc(1 * @@share1)
		 GetLongResource(@@res3)
		 exc(4)
		 ReleaseLongResource(@@res3)
		 exc(13 * @@share1)
	 end
	 @@share2 = 1.0
	 def task2
		 exc(33 * @@share2)
		 GetShortResource(@@res8)
		 exc(3)
		 ReleaseShortResource(@@res8)
		 exc(5 * @@share2)
		 GetShortResource(@@res2)
		 exc(2)
		 ReleaseShortResource(@@res2)
		 GetLongResource(@@res1)
		 exc(1)
		 ReleaseLongResource(@@res1)
		 exc(1 * @@share2)
	 end
	 def task6
		 exc(15 * @@share2)
		 GetShortResource(@@res6)
		 exc(4)
		 ReleaseShortResource(@@res6)
		 exc(1 * @@share2)
		 GetShortResource(@@res8)
		 exc(3)
		 ReleaseShortResource(@@res8)
		 GetShortResource(@@res6)
		 exc(3)
		 ReleaseShortResource(@@res6)
		 exc(8 * @@share2)
	 end
	 def task10
		 exc(7 * @@share2)
		 GetLongResource(@@res3)
		 exc(4)
		 ReleaseLongResource(@@res3)
		 exc(1 * @@share2)
		 GetLongResource(@@res7)
		 exc(2)
		 ReleaseLongResource(@@res7)
		 exc(16 * @@share2)
		 GetLongResource(@@res3)
		 exc(4)
		 ReleaseLongResource(@@res3)
		 exc(1 * @@share2)
	 end
	 def task14
		 exc(11 * @@share2)
		 GetLongResource(@@res5)
		 exc(4)
		 ReleaseLongResource(@@res5)
		 exc(21 * @@share2)
		 GetLongResource(@@res3)
		 exc(4)
		 ReleaseLongResource(@@res3)
		 GetLongResource(@@res1)
		 exc(2)
		 ReleaseLongResource(@@res1)
		 exc(9 * @@share2)
	 end
	 @@share3 = 1.0
	 def task3
		 exc(18 * @@share3)
		 GetLongResource(@@res5)
		 exc(4)
		 ReleaseLongResource(@@res5)
		 exc(6 * @@share3)
		 GetLongResource(@@res1)
		 exc(2)
		 ReleaseLongResource(@@res1)
		 exc(8 * @@share3)
		 GetLongResource(@@res1)
		 exc(2)
		 ReleaseLongResource(@@res1)
		 exc(2 * @@share3)
	 end
	 def task7
		 exc(14 * @@share3)
		 GetShortResource(@@res2)
		 exc(2)
		 ReleaseShortResource(@@res2)
		 exc(8 * @@share3)
		 GetLongResource(@@res5)
		 exc(4)
		 ReleaseLongResource(@@res5)
		 exc(1 * @@share3)
		 GetShortResource(@@res4)
		 exc(3)
		 ReleaseShortResource(@@res4)
		 exc(1 * @@share3)
	 end
	 def task11
		 exc(8 * @@share3)
		 GetLongResource(@@res1)
		 exc(3)
		 ReleaseLongResource(@@res1)
		 exc(34 * @@share3)
		 GetLongResource(@@res7)
		 exc(2)
		 ReleaseLongResource(@@res7)
		 exc(8 * @@share3)
		 GetLongResource(@@res7)
		 exc(1)
		 ReleaseLongResource(@@res7)
		 exc(3 * @@share3)
	 end
	 def task15
		 exc(25 * @@share3)
		 GetShortResource(@@res6)
		 exc(4)
		 ReleaseShortResource(@@res6)
		 exc(7 * @@share3)
		 GetLongResource(@@res7)
		 exc(1)
		 ReleaseLongResource(@@res7)
		 exc(1 * @@share3)
		 GetLongResource(@@res1)
		 exc(3)
		 ReleaseLongResource(@@res1)
		 exc(1 * @@share3)
	 end
	 @@share4 = 1.0
	 def task4
		 GetLongResource(@@res7)
		 exc(1)
		 ReleaseLongResource(@@res7)
		 exc(17 * @@share4)
		 GetLongResource(@@res3)
		 exc(1)
		 ReleaseLongResource(@@res3)
		 exc(2 * @@share4)
		 GetLongResource(@@res5)
		 exc(4)
		 ReleaseLongResource(@@res5)
		 exc(13 * @@share4)
	 end
	 def task8
		 exc(25 * @@share4)
		 GetShortResource(@@res4)
		 exc(4)
		 ReleaseShortResource(@@res4)
		 exc(5 * @@share4)
		 GetLongResource(@@res3)
		 exc(1)
		 ReleaseLongResource(@@res3)
		 exc(1 * @@share4)
		 GetLongResource(@@res5)
		 exc(4)
		 ReleaseLongResource(@@res5)
		 exc(1 * @@share4)
	 end
	 def task12
		 exc(14 * @@share4)
		 GetShortResource(@@res6)
		 exc(1)
		 ReleaseShortResource(@@res6)
		 exc(30 * @@share4)
		 GetLongResource(@@res3)
		 exc(1)
		 ReleaseLongResource(@@res3)
		 exc(4 * @@share4)
		 GetLongResource(@@res7)
		 exc(3)
		 ReleaseLongResource(@@res7)
		 exc(2 * @@share4)
	 end
	 def task16
		 exc(6 * @@share4)
		 GetLongResource(@@res7)
		 exc(4)
		 ReleaseLongResource(@@res7)
		 exc(4 * @@share4)
		 GetShortResource(@@res6)
		 exc(3)
		 ReleaseShortResource(@@res6)
		 GetLongResource(@@res5)
		 exc(4)
		 ReleaseLongResource(@@res5)
		 exc(12 * @@share4)
	 end
end
